version: "3.7"

volumes:
  postgres_volume:

services:
  crud-books:
    build: ./
    command: ["./wait-for-postgres.sh", "./crud-books"]
    ports:
      - 8080:8080
    depends_on:
      - db
    environment:
      - TZ=Europe/Moscow
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_NAME=postgres
      - DB_SSLMODE=disable
      - DB_PASSWORD=qwerty
  db:
    restart: always
    image: postgres:latest
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=qwerty
    ports:
      - 5432:5432
