version: "3.8"

volumes:
  postgres_volume:

services:
  crud-books:
    restart: always
    build: ./
    command: ["./wait-for-postgres.sh", "db", "./crud-books"]
    ports:
      - 8000:8000
    depends_on:
      - db
    environment:
      - DB_PASSWORD=qwerty
  db:
    restart: always
    image: postgres:latest
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=qwerty
    ports:
      - 5432:5432
